<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTutN1EA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTutN1EA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTutN1EA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTutN1EA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTutN1EA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TutN1EA',
    'container.build_id' => '13ff515a',
    'container.build_time' => 1559200355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTutN1EA');
