<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSUFPtiN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSUFPtiN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSUFPtiN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSUFPtiN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSUFPtiN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SUFPtiN',
    'container.build_id' => 'ff3c5280',
    'container.build_time' => 1558963453,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSUFPtiN');
