<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8FivVEw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8FivVEw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8FivVEw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8FivVEw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8FivVEw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8FivVEw',
    'container.build_id' => 'f37d8cde',
    'container.build_time' => 1558967435,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8FivVEw');
